/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as ConversationsRouteImport } from "./routes/conversations"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ConversationsIndexRouteImport } from "./routes/conversations/index"
import { Route as ConversationsConversationIdRouteImport } from "./routes/conversations/$conversationId"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: "/conversations",
  path: "/conversations",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ConversationsRoute,
} as any)
const ConversationsConversationIdRoute =
  ConversationsConversationIdRouteImport.update({
    id: "/$conversationId",
    path: "/$conversationId",
    getParentRoute: () => ConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/conversations": typeof ConversationsRouteWithChildren
  "/login": typeof LoginRoute
  "/conversations/$conversationId": typeof ConversationsConversationIdRoute
  "/conversations/": typeof ConversationsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/conversations/$conversationId": typeof ConversationsConversationIdRoute
  "/conversations": typeof ConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/conversations": typeof ConversationsRouteWithChildren
  "/login": typeof LoginRoute
  "/conversations/$conversationId": typeof ConversationsConversationIdRoute
  "/conversations/": typeof ConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/conversations"
    | "/login"
    | "/conversations/$conversationId"
    | "/conversations/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/login" | "/conversations/$conversationId" | "/conversations"
  id:
    | "__root__"
    | "/"
    | "/conversations"
    | "/login"
    | "/conversations/$conversationId"
    | "/conversations/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsRoute: typeof ConversationsRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conversations": {
      id: "/conversations"
      path: "/conversations"
      fullPath: "/conversations"
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conversations/": {
      id: "/conversations/"
      path: "/"
      fullPath: "/conversations/"
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof ConversationsRoute
    }
    "/conversations/$conversationId": {
      id: "/conversations/$conversationId"
      path: "/$conversationId"
      fullPath: "/conversations/$conversationId"
      preLoaderRoute: typeof ConversationsConversationIdRouteImport
      parentRoute: typeof ConversationsRoute
    }
  }
}

interface ConversationsRouteChildren {
  ConversationsConversationIdRoute: typeof ConversationsConversationIdRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
}

const ConversationsRouteChildren: ConversationsRouteChildren = {
  ConversationsConversationIdRoute: ConversationsConversationIdRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
}

const ConversationsRouteWithChildren = ConversationsRoute._addFileChildren(
  ConversationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsRoute: ConversationsRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
